title: Homelab Club at UMD
description: >- # this means to ignore newlines until "baseurl:"
  Homelab Club at UMD
# url: "https://suddenlysixam.github.io"
# url: "https://suddenlysixam.club"
# baseurl: "/umd-homelab"
repository: suddenlysixam/umd-homelab

author:
  type: organization
  name: Homelab Club at UMD
  url: https://suddenlysixam.club/
  avatar: assets/apple-touch-icon.png
  github: suddenlysixam/umd-homelab
  linkedin: company/homelab-club-at-umd

remote_theme: https://github.com/suddenlysixam/jekyll-TeXt-theme
# text_skin: dark
# highlight_theme: tomorrow-night
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

lang: en
timezone: America/New_York
future: true

toc:
  selectors: "h1,h2,h3"

# paginate: 8
# paginate_path: /page:num

search:
  provider: default

collections:
  authors:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "article"
      show_date: false
      show_author_profile: true
  - scope:
      path: "projects"
    values:
      layout: "article"
      show_author_profile: false
      sidebar:
        cat: [knowledge, projects]
      aside:
        toc: true
      permalink: /projects/:title:output_ext
      categories: projects
  - scope:
      path: "knowledge"
    values:
      layout: "article"
      show_author_profile: false
      sidebar:
        cat: [knowledge, projects]
      aside:
        toc: true
      permalink: /knowledge/:title:output_ext
      categories: knowledge

sources: unpkg
